---
title: "map"
author: "Catarina Pien"
date: '2023-03-28'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(deltamapr)
library(ggplot2)
library(deltafish)
library(dplyr)
library(sf)
```

Save 20mm and SLS stations
```{r}
# clear_cache()
# create_fish_db()
con <- open_database()
surv <- open_survey(con)
surv_20_sls_bay <- surv %>%
  filter(Source %in% c("20mm", "SLS", "Bay Study")) %>%
  select(Station, Latitude, Longitude, Source) %>%
  collect()

survloc_sf <- surv_20_sls_bay %>% 
  distinct() %>%
  filter(!is.na(Longitude)) %>%
  st_as_sf(coords = c("Longitude", "Latitude"),
           crs = 4326, remove = FALSE)

survall <- survloc_sf %>%
  group_by(Station) %>%
  slice(1) %>%
  ungroup()

twentymm <- survloc_sf %>%
  filter(Source == "20mm") %>%
  distinct()

sls <- survloc_sf %>%
  filter(Source == "SLS") %>%
  distinct()

bay <- survloc_sf %>%
  filter(Source == "Bay Study") %>%
  distinct()


```

Region Phase 3
```{r}
(map3 <- ggplot() + 
   geom_sf(data = WW_Delta, color = "darkslategray3") +
   geom_sf(data = R_EDSM_Regions_19P3, aes(fill = Region), alpha = 0.3, inherit.aes = FALSE)+
   geom_sf(data = survall, color = "gray40") + 
   geom_sf_text(data = survall, mapping = aes(label = Station), size = 3, nudge_x = -0.012, nudge_y = 0.02) + 
     scale_x_continuous(limits = c(-122.45, -121.3)) + 
   scale_y_continuous(limits = c(37.73, 38.65)) +
 # annotation_north_arrow(location = "tl", which_north = "true",
 #                            pad_x = unit(.1, "in"), pad_y = unit(0.2, "in"),
 #                            style = north_arrow_fancy_orienteering) +
  #    annotation_scale(location = "bl", bar_cols = c("black", "white", "black", "white")) +
   labs(title = "Phase 3") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, vjust = 0.5)))
```


Strata Phase 3

```{r}
(map_s3 <- ggplot() + 
  geom_sf(data = WW_Delta, color = "darkslategray3") +
   geom_sf(data = R_EDSM_Strata_19P3, aes(fill = Stratum), alpha = 0.4,inherit.aes = FALSE)+
 geom_sf(data = survall, color = "gray40") + 
   geom_sf_text(data = survall, mapping = aes(label = Station), size = 3, nudge_x = -0.05, nudge_y = 0.02) +
 # annotation_north_arrow(location = "tl", which_north = "true",
 #                            pad_x = unit(.1, "in"), pad_y = unit(0.2, "in"),
 #                            style = north_arrow_fancy_orienteering) +
  #    annotation_scale(location = "bl", bar_cols = c("black", "white", "black", "white")) +
     scale_x_continuous(limits = c(-122.45, -121.3)) + 
   scale_y_continuous(limits = c(37.75, 38.65)) +
   labs(title = "Strata Phase 3") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, vjust = 0.5)))
```


Region Phase 1 - 2017-2018
```{r}
(map_r1 <- ggplot() + 
  geom_sf(data = WW_Delta, color = "darkslategray3") +
   geom_sf(data = R_EDSM_Regions_1718P1, aes(fill = Region), alpha = 0.5,inherit.aes = FALSE)+
 geom_sf(data = survall, color = "gray30", size = 0.7) + 
   geom_sf_text(data = survall, mapping = aes(label = Station), size = 2.5, nudge_x = -0.012, nudge_y = 0.016) +
 # annotation_north_arrow(location = "tl", which_north = "true",
 #                            pad_x = unit(.1, "in"), pad_y = unit(0.2, "in"),
 #                            style = north_arrow_fancy_orienteering) +
  #    annotation_scale(location = "bl", bar_cols = c("black", "white", "black", "white")) +
     scale_x_continuous(limits = c(-122.45, -121.3)) + 
   scale_y_continuous(limits = c(37.5, 38.65)) +
   viridis::scale_fill_viridis(option = "turbo", discrete = TRUE) + 
   labs(title = "Region Phase 1 2017-2018") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.position = "top"))
```



Strata Phase 1 (older; includes upper sac) - 2017-2018
```{r}
(map_s1 <- ggplot() + 
  geom_sf(data = WW_Delta, color = "darkslategray3") +
   geom_sf(data = R_EDSM_Strata_1718P1, aes(fill = Stratum), alpha = 0.5,inherit.aes = FALSE)+
 geom_sf(data = survall, color = "gray30", size = 0.7) + 
   geom_sf_text(data = survall, mapping = aes(label = Station), size = 2.5, nudge_x = -0.012, nudge_y = 0.016) +
 # annotation_north_arrow(location = "tl", which_north = "true",
 #                            pad_x = unit(.1, "in"), pad_y = unit(0.2, "in"),
 #                            style = north_arrow_fancy_orienteering) +
  #    annotation_scale(location = "bl", bar_cols = c("black", "white", "black", "white")) +
     scale_x_continuous(limits = c(-122.45, -121.3)) + 
   scale_y_continuous(limits = c(37.5, 38.65)) +
   viridis::scale_fill_viridis(option = "turbo", discrete = TRUE) + 
   labs(title = "Strata Phase 1 2017-2018") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.position = "top"))


```






```{r}
png(here::here("figures","stations_regions_phase1.png"),
     type="cairo",
     units="in", 
     width=7, 
     height=7, 
     pointsize=5, 
     res=300)
print(map_r1)
dev.off()

png(here::here("figures","stations_strata_phase1.png"),
     type="cairo",
     units="in", 
     width=9, 
     height=7, 
     pointsize=6, 
     res=300)
print(map_s1)
dev.off()



```

```{r}
survall_sf <- st_transform(survall, crs = st_crs(R_EDSM_Strata_1718P1))
station_stratum <- st_join(survall_sf, R_EDSM_Strata_1718P1) %>%
  mutate(Stratum = replace(Stratum, is.na(Stratum) & Source == "Bay Study", "Bay"))
station_regions <- st_join(survall_sf, R_EDSM_Regions_1718P1) %>%
  mutate(Region = replace(Region, is.na(Region) & Source == "Bay Study", "Bay"))

readr::write_csv(station_stratum, here::here("data_clean/station_stratum_crosswalk.csv"))
readr::write_csv(station_regions, here::here("data_clean/station_region_crosswalk.csv"))
```

Interactive
```{r}
library(leaflet)
library(mapview)
mapView(survall, zcol = "Station", legend = FALSE, label = TRUE) +
mapView(R_EDSM_Strata_1819P1, zcol = "Stratum") 
```

