---
title: "Untitled"
author: "Catarina Pien"
date: '2023-02-16'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(lubridate)
library(ggplot2)
library(dplyr)
library(tidyr)
library(dataRetrieval)
library(sharpshootR)
library(here)
source("functions.R")
```

```{r}
wytype <- read.csv("data_raw/WYType.csv") %>%
  select(WY, Basin, Yr.type) %>%
  mutate(wy = as.numeric(WY)) %>%
  pivot_wider(names_from = "Basin", values_from = Yr.type, id_cols = "wy")
```

```{r}
Sys.setenv(TZ = 'America/Los_Angeles')
```

```{r}
startDate = today()-9
endDate = today() -1
```

# Download Wind Data
* FRK, ANH, RRI, MSD, SJR, 
```{r}
wind.dir<- CDECquery("FRK", "10", "E", start = startDate,
                              end = endDate)
wind.sp<- CDECquery("FRK", "9", "E", start = startDate,
                              end = endDate)

wind_speed <- bind_rows(wind.sp)%>%
    mutate(wind_speed = value,
           datetime = ymd_hms(datetime),
           date = date(datetime),
           month = as.numeric(month)) %>%
  select(datetime,date,month, wy = water_year, station = station_id, wind_speed) %>%
  filter(!is.na(station),
         !is.na(date))

wind_dir <- bind_rows(wind.dir)%>%
    mutate(wind_dir = value,
           datetime = ymd_hms(datetime),
           date = date(datetime),
           month = as.numeric(month)) %>%
  select(datetime,date,month, wy = water_year, station = station_id, wind_dir) %>%
  filter(!is.na(station),
         !is.na(date))

wind_df <- left_join(wind_speed, wind_dir)
saveRDS(wind_cf, "data_raw/wind_FRK_2000_2022.rds")
```

# Download Flow Data
```{r}

OSJ.flow<- f_get_NWIS_flow(siteNumbers = 11313452, startDate = startDate, endDate = endDate)

flow_OSJ <- readRDS(here("data_raw", "USGS_NWIS_11313452_flow.rds")) %>%
  rename(Datetime = date_time, 
         flow = flow_inst)%>%
  mutate(station = "OSJ",
         date = date(Datetime),
         datetime = Datetime) %>%
  select(datetime, date, station, flow) %>%
  pivot_longer(cols = flow,
               names_to = "parameter",
               values_to = "flow_OSJ") 
```


# Download Turbidity Data
```{r}
stations_turb <- c("FRK")
stations_turb2 <- c("OBI", "HOL", "SJJ", "TSL", "OH4")

turb <- lapply(stations_turb,
                 function(x){
                 CDECquery(id = x, sensor = 27, interval = "E", start = startDate,
                              end = endDate)})
turb_df <- bind_rows(turb)%>%
    mutate(turbidity = value,
           datetime = ymd_hms(datetime),
           date = date(datetime),
           month = as.numeric(month)) %>%
  filter(turbidity>=0) %>%
  select(datetime,date,month, wy = water_year, station = station_id, turbidity) %>%
  filter(!is.na(station),
         !is.na(date))

turb2 <- lapply(stations_turb2,
                 function(x){
                 CDECquery(id = x, sensor = 221, interval = "E", start = startDate,
                              end = endDate)})
turb_df2 <- bind_rows(turb2)%>%
    mutate(turbidity = value,
           datetime = ymd_hms(datetime),
           date = date(datetime),
           month = as.numeric(month)) %>%
  filter(turbidity>0) %>%
  select(datetime,date,month, wy = water_year, station = station_id, turbidity) %>%
  filter(!is.na(station),
         !is.na(date))

turb_combined <- rbind(turb_df, turb_df2) %>%
  filter(turbidity < 150)

#saveRDS(turb_combined, "data_raw/turbidity_cdec_southdelta_2000-2022.rds")
#turb_combined <- readRDS("data_raw/turbidity_cdec_southdelta_2000-2022.rds")
```

```{r}
turb_wide <- turb_combined %>%
  pivot_wider(names_from = "station", values_from = turbidity)
```

# Calculate Daily average - Don't need to rerun
```{r}
#turb_clean <- readRDS("data_clean/clean_turbidity_south_delta_event.rds")
daily_turb <- turb_combined %>%
  group_by(date, month, wy,  station) %>%
  summarize(meanTurb = mean(turbidity)) %>%
  ungroup() 
```

## Plot data
```{r}
ggplot(turb_combined) + geom_point(aes(datetime, turbidity)) +facet_wrap(~station, nrow = 3)

(plot_turbidity <- ggplot(daily_turb, aes(date, meanTurb)) + 
    geom_line() + 
    geom_point(size = 0.8) + 
  facet_wrap(~station, scales = "free_y", nrow = 3) +
  viridis::scale_color_viridis(option = "turbo", discrete = TRUE) + 
  theme_bw() +
    theme(strip.text = element_text(size = 7.5),
          axis.text = element_text(size = 9),
          axis.title.x = element_blank()))
```

# Combine with wind data and flow data 

* No flow at FRK so used OSJ

```{r}
data <- left_join(turb_wide, wind_df) %>%
  select(-station) %>%
  filter(date < date("2023-02-17"))

turb_wind_long <- data %>%
  pivot_longer(cols = c(FRK:wind_dir), names_to = "parameter", values_to = "value")%>%
  mutate(parameter = factor(parameter, levels = c("wind_speed", "TSL", "SJJ", "FRK", "OBI", "HOL", "OH4", "wind_dir")))

turb_wind_daily <- turb_wind_long %>%
  group_by(wy, month, date,  parameter) %>%
  summarize(dailyMax = max(value, na.rm = TRUE),
            dailyMean = mean(value, na.rm = TRUE),
            dailyMin = min(value, na.rm = TRUE))  

backto_wide <- turb_wind_daily %>%
  pivot_wider(names_from = "parameter", values_from = c("dailyMean", "dailyMax", "dailyMin"))
```

### Plots
```{r}
dummy <- data.frame(parameter = factor(c("wind_speed", "TSL", "SJJ", "FRK", "OBI", "HOL", "OH4", "wind_dir")),
                    Z = c(20, 12, 12, 12, 12, 12, 12, NA))

(plot_turb_wind_daily <- ggplot() + 
  geom_line(data = turb_wind_daily, aes(date, dailyMean)) + 
    geom_point(data = turb_wind_daily, aes(date, dailyMean, color = factor(date)), size = 2) + 
  
 facet_wrap(~parameter, scales = "free_y", nrow = 8,
             labeller = as_labeller(c(
    `wind_speed` = "FRK Wind Speed", `TSL` = "Turb TSL", `SJJ` = "Turb SJJ", `FRK` = "Turb FRK", `OBI` = "Turb OBI",
    HOL = "Turb HOL", OH4 = "Turb OH4",  wind_dir = "FRK Wind Dir"))) +
  geom_hline(data = dummy, aes(yintercept = Z), color = "red")+
  viridis::scale_color_viridis(discrete = TRUE, option = "turbo") + 
  scale_x_date(date_breaks = "1 day", date_labels = "%m/%d") + theme_bw() + theme(axis.text.x = element_text(angle = 90),
                                                           legend.position = "none"))

(plot_turb_wind_event <- ggplot(turb_wind_long) + 
  geom_point(aes(datetime, value, color = factor(date)), size = 0.5) + 
   geom_line(aes(datetime, value, color = factor(date))) + 
  facet_wrap(~parameter, scales = "free_y", nrow = 8,
             labeller = as_labeller(c(
    `wind_speed` = "FRK Wind Speed", `TSL` = "Turb TSL", `SJJ` = "Turb SJJ", `FRK` = "Turb FRK", `OBI` = "Turb OBI", OH4 = "Turb OH4",
    HOL = "Turb HOL",wind_dir = "FRK Wind Dir"))) +
    geom_hline(data = dummy, aes(yintercept = Z), color = "red")+
   scale_x_datetime(date_breaks = "1 day", date_labels = "%m/%d") +
  viridis::scale_color_viridis(discrete = TRUE, option = "turbo") + 
  theme_bw() + theme(axis.text.x = element_text(angle = 90),
                     legend.position = "none"))
```

```{r}
png(filename = here("figures", "wind_turbidity_daily.png"), width = 8, height = 10, units = "in", pointsize = 9, family = "sans", res = 300)
plot_turb_wind_daily
dev.off()


png(filename = here("figures", "wind_turbidity_event.png"), width = 8, height = 10, units = "in", pointsize = 9, family = "sans", res = 300)
plot_turb_wind_event
dev.off()
```

